/**
 * Programmatic SEO Industry + City Route
 *
 * Handles thousands of generated SEO pages for organic search traffic.
 * Example: /seo/real-estate/miami -> Real Estate Agents in Miami
 *
 * This is specifically for programmatic SEO pages generated by the SEO engine.
 */

import type { MetaFunction, LoaderFunctionArgs } from "@remix-run/cloudflare";
import { json } from "@remix-run/cloudflare";
import { useLoaderData, Link } from "@remix-run/react";
import { MapPin, Star, Phone, Mail, ExternalLink, Search, TrendingUp, ChevronRight } from "lucide-react";
import { generatePageContent } from "~/lib/seo-engine";

export const meta: MetaFunction<typeof loader> = ({ data }) => {
  if (!data || !data.seoPage) {
    return [{ title: "Page Not Found | EstateFlow" }];
  }

  return [
    { title: data.seoPage.title },
    { name: "description", content: data.seoPage.metaDescription },
    // Open Graph
    { property: "og:title", content: data.seoPage.title },
    { property: "og:description", content: data.seoPage.metaDescription },
    { property: "og:type", content: "website" },
    // Schema.org
    {
      "script:ld+json": {
        "@context": "https://schema.org",
        "@type": "ProfessionalService",
        "name": data.seoPage.h1Headline,
        "address": {
          "@type": "PostalAddress",
          "addressLocality": data.seoPage.city,
          "addressRegion": data.seoPage.state,
          "addressCountry": "US"
        },
        "aggregateRating": {
          "@type": "AggregateRating",
          "ratingValue": data.stats.avgRating,
          "reviewCount": data.stats.totalReviews
        }
      }
    }
  ];
};

export async function loader({ params, context }: LoaderFunctionArgs) {
  const { industry, city } = params;

  if (!industry || !city) {
    throw new Response("Not Found", { status: 404 });
  }

  const db = context.env.DB;

  // Get SEO page data
  const slug = `${industry}/${city}`;
  const seoPage = await db
    .prepare('SELECT * FROM seo_pages WHERE slug = ?')
    .bind(slug)
    .first<{
      id: string;
      slug: string;
      title: string;
      metaDescription: string;
      h1Headline: string;
      contentJson: string;
      city: string;
      state: string;
      industry: string;
    }>();

  if (!seoPage) {
    throw new Response("Page Not Found", { status: 404 });
  }

  // Generate/update page content with real data
  const updatedPage = await generatePageContent(seoPage.id, context);

  // Get professionals for this location
  const professionals = await db
    .prepare(`
      SELECT
        id, name, slug, city, state, specializations,
        license_number, years_experience, avg_rating,
        total_reviews, phone, email, profile_image_url
      FROM professionals
      WHERE industry = ?
        AND city = ?
        AND state = ?
        AND status = 'active'
      ORDER BY avg_rating DESC, total_reviews DESC
      LIMIT 50
    `)
    .bind(industry, seoPage.city, seoPage.state)
    .all<{
      id: string;
      name: string;
      slug: string;
      city: string;
      state: string;
      specializations: string;
      license_number: string;
      years_experience: number;
      avg_rating: number;
      total_reviews: number;
      phone: string;
      email: string;
      profile_image_url: string;
    }>();

  // Parse content
  const content = JSON.parse(updatedPage.contentJson || '{}');

  // Calculate stats
  const stats = {
    totalProfessionals: professionals.results.length,
    avgRating: professionals.results.length > 0
      ? professionals.results.reduce((sum, p) => sum + (p.avg_rating || 0), 0) / professionals.results.length
      : 0,
    totalReviews: professionals.results.reduce((sum, p) => sum + (p.total_reviews || 0), 0)
  };

  return json({
    seoPage: updatedPage,
    professionals: professionals.results,
    content,
    stats,
    industryName: getIndustryName(industry),
    cityName: city.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
  });
}

export default function SEOIndustryCityPage() {
  const { seoPage, professionals, stats, industryName, cityName } = useLoaderData<typeof loader>();

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="flex items-center gap-2 text-blue-100 text-sm mb-4">
            <Link to="/" className="hover:text-white transition-colors">Home</Link>
            <span>/</span>
            <Link to={`/${seoPage.industry}`} className="hover:text-white transition-colors">
              {industryName}
            </Link>
            <span>/</span>
            <span>{cityName}</span>
          </div>

          <h1 className="text-4xl lg:text-5xl font-bold mb-4">
            {seoPage.h1Headline}
          </h1>
          <p className="text-xl text-blue-100 max-w-3xl">
            {seoPage.metaDescription}
          </p>

          {/* Quick Stats */}
          <div className="grid grid-cols-3 gap-6 mt-8 max-w-2xl">
            <div className="bg-white/10 backdrop-blur rounded-lg p-4">
              <div className="text-3xl font-bold">{stats.totalProfessionals}</div>
              <div className="text-sm text-blue-100">Professionals</div>
            </div>
            <div className="bg-white/10 backdrop-blur rounded-lg p-4">
              <div className="text-3xl font-bold">{stats.avgRating.toFixed(1)}</div>
              <div className="text-sm text-blue-100">Avg Rating</div>
            </div>
            <div className="bg-white/10 backdrop-blur rounded-lg p-4">
              <div className="text-3xl font-bold">{stats.totalReviews}</div>
              <div className="text-sm text-blue-100">Reviews</div>
            </div>
          </div>
        </div>
      </section>

      {/* Search Bar */}
      <section className="bg-white border-b border-slate-200 sticky top-0 z-10 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex gap-4 items-center">
            <div className="flex-1 relative">
              <Search className="absolute left-4 top-3 w-5 h-5 text-slate-400" />
              <input
                type="text"
                placeholder={`Search ${industryName} in ${cityName}...`}
                className="w-full pl-12 pr-4 py-2.5 rounded-lg border border-slate-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none"
              />
            </div>
            <button className="px-6 py-2.5 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors">
              Search
            </button>
          </div>
        </div>
      </section>

      {/* Professionals List */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="flex items-center justify-between mb-8">
          <h2 className="text-2xl font-bold text-slate-900">
            Top {industryName} in {cityName}
          </h2>
          <div className="flex items-center gap-2 text-sm text-slate-600">
            <TrendingUp className="w-4 h-4" />
            <span>Sorted by rating & reviews</span>
          </div>
        </div>

        {professionals.length === 0 ? (
          <div className="text-center py-16">
            <div className="text-slate-600 mb-4">
              No professionals found in this area yet.
            </div>
            <Link
              to="/claim"
              className="inline-flex items-center gap-2 px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition-colors"
            >
              Be the first to claim your profile
              <ExternalLink className="w-4 h-4" />
            </Link>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 gap-6">
            {professionals.map((professional) => (
              <Link
                key={professional.id}
                to={`/professional/${professional.slug}`}
                className="group bg-white rounded-xl border border-slate-200 hover:border-blue-300 hover:shadow-lg transition-all p-6"
              >
                <div className="flex gap-4">
                  {/* Avatar */}
                  <div className="w-16 h-16 bg-slate-200 rounded-full flex-shrink-0 overflow-hidden">
                    {professional.profile_image_url ? (
                      <img
                        src={professional.profile_image_url}
                        alt={professional.name}
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      <div className="w-full h-full flex items-center justify-center text-slate-400 text-xl font-semibold">
                        {professional.name.charAt(0)}
                      </div>
                    )}
                  </div>

                  {/* Info */}
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-slate-900 group-hover:text-blue-600 transition-colors mb-1">
                      {professional.name}
                    </h3>

                    {/* Rating */}
                    {professional.total_reviews > 0 && (
                      <div className="flex items-center gap-2 mb-2">
                        <div className="flex items-center gap-1">
                          <Star className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                          <span className="font-medium text-slate-900">
                            {professional.avg_rating.toFixed(1)}
                          </span>
                        </div>
                        <span className="text-sm text-slate-500">
                          ({professional.total_reviews} reviews)
                        </span>
                      </div>
                    )}

                    {/* Specializations */}
                    {professional.specializations && (
                      <div className="text-sm text-slate-600 mb-2">
                        {JSON.parse(professional.specializations).slice(0, 2).join(', ')}
                      </div>
                    )}

                    {/* Experience */}
                    {professional.years_experience > 0 && (
                      <div className="text-sm text-slate-500">
                        {professional.years_experience} years experience
                      </div>
                    )}

                    {/* Contact */}
                    <div className="flex gap-4 mt-3">
                      {professional.phone && (
                        <div className="flex items-center gap-1 text-sm text-slate-600">
                          <Phone className="w-3 h-3" />
                          <span>Call</span>
                        </div>
                      )}
                      {professional.email && (
                        <div className="flex items-center gap-1 text-sm text-slate-600">
                          <Mail className="w-3 h-3" />
                          <span>Email</span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 text-center">
          <h2 className="text-3xl font-bold mb-4">
            Are you a {industryName.slice(0, -1)} in {cityName}?
          </h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Claim your free profile and start getting more leads today.
            Join thousands of professionals using EstateFlow to grow their business.
          </p>
          <Link
            to="/claim"
            className="inline-flex items-center gap-2 px-8 py-4 bg-white text-blue-600 font-semibold rounded-xl hover:bg-blue-50 transition-all shadow-xl"
          >
            Claim Your Free Profile
            <ChevronRight className="w-5 h-5" />
          </Link>
        </div>
      </section>
    </div>
  );
}

// Helper function to get industry display name
function getIndustryName(industryId: string): string {
  const industries: Record<string, string> = {
    'real_estate': 'Real Estate Agents',
    'legal': 'Attorneys',
    'insurance': 'Insurance Agents',
    'mortgage': 'Mortgage Lenders',
    'financial': 'Financial Advisors',
    'contractor': 'Contractors'
  };

  return industries[industryId] || industryId;
}
